### PR TITLE
Add --all option and "best" quality

### PR DESCRIPTION
**Pull request by tristan**
Just some adjustments I made after using the tool, in case you'd like to include them in your own code.

### `--all` 

I wanted to download everything in my library! thus `--all`

### `--quality best`

I had some files that when downloaded were just a text file with the content
> Dieses Audioformat wird nicht unterstützt. Bitte laden Sie den Titel in einem anderen Audioformat herunter

This is because those books didn't have the `LC_128_44100_stereo` quality, so I changed some things to fetch all the available qualitys and allow picking the best one, or verifying the requested one exists, and if not pick the next best.

### renaming checks

When overwriting, at least on Windows, I got the error:
```
FileExistsError: [WinError 183] Cannot create a file when that file already exists: <filename>
```

I added the additional renaming functionality to work around this

### Exception logging in `consume`

After the above error, the app would just hang, and not say anything. This is because the coroutine raised an uncaught exception and never hit the `queue.task_done()` line, so ` await queue.join()` never completed. The error was also never reported until after Ctrl+C was used (this is a common issue with tasks created with `asyncio.ensure_future` and `asyncio.create_task`). This at least reports the exception, and lets other tasks continue on.

### CODE REVIEW

**Comment by mkb79** [comment]
Thank you (Danke!) for your pr. I‘m happy about everyone who helps!

I take a short look on it and almost are fine. I will test it later this day. 

I still learning writing async code, so I have a question. You made :func:`get_quality` async but I don‘t see any async code in it. What is the reason for this? If you want, you can contact me via mail (mkb79@hackitall.de) too. 

Greets

**Comment by tristan** [comment]
aha! good catch!
This is because I had an earlier iteration of the method that fetched the qualities with the `api_client` using `1.0/library/{asin}`.
So it originally looked like this:
```
async def get_quality(self):
    params = {
        "response_groups": "product_attrs,relationships"
    }
    r = await self._api_client.get(f"/1.0/library/{self.asin}",
                                   params=params)
    best = (None, 0, 0)
    for codec in r["item"]["available_codecs"]:
...
```
And when I changed it to user `self._data` instead i forgot to remove the `async` part.
It does not need to be async anymore.
I will update it.

**Comment by mkb79** [comment]
I found an issue in your code in the `get_quality` class method. 

You write:

```python
for codec in self._data["available_codecs"]:
    if verify is not None and verified is False:
        if verify == codec["enhanced_codec"]:
            return verify
```

The var `verified` doesn‘t exists. 

You could write instead:

```python
for codec in self.available_codecs:
    if verify == codec["enhanced_codec"]:
        return verify
```

**Comment by tristan** [comment]
👍 Updated. I left in the check for whether `verify is not None` as I like to avoid the potential random bad case where `codec["enhanced_codec"]` being `None` confusing things. even if the chance of that happening is basically 0.

**Pull request merged**
