### PR TITLE
Add `-c, --remove-intro-outro` option to `decrypt`

### LINKED ISSUE #170: `decrypt` option to remove Audible intro and outro
The `decrypt` subcommand already has an option `-s, --separate-intro-outro` to separate the Audible branding into separate Intro and Outro chapters.

It would be great if there were also an option to remove them altogether.

Some previous discussion in https://github.com/mkb79/audible-cli/issues/154.

---

Looking through the ffmpeg [documentation](http://ffmpeg.org/ffmpeg-all.html#toc-Main-options), it seems the `-ss [first_chapter_start] -i input.aax -to [last_chapter_end]` options could be used.

There's also some examples in the [wiki](https://trac.ffmpeg.org/wiki/Seeking#Cuttingsmallsections) and more details on [StackExchange](https://superuser.com/questions/377343/cut-part-from-video-file-from-start-position-to-end-position-with-ffmpeg).

### PR DESCRIPTION
**Pull request by vwkd**
This adds a `-c, --remove-intro-outro` option to the `decrypt` subcommand that removes the Audible brand intro and outro. It can't be used together with the `-s, --separate-intro-outro` option.

I mainly followed the example in the [wiki](https://trac.ffmpeg.org/wiki/Seeking#Cuttingsmallsections). I chose `-t` with a duration instead of `-to` with a timestamp, because it doesn't depend on the location of `-ss` with respect to `-i`. `-ss` resets the timestamps to 0 if it's before `-i` but not if it's after. `-t` continues to work the same, while `-to` would need to adapt.

Closes #170.

### CODE REVIEW

**Comment by vwkd** [comment]
Found the bug now. ffmpeg seems very sensitive to the location of the input. I had overlooked that there are two inputs, and had mistaken the metafile `-i` for the source `-i`. Moving the metafile `-i` after the `-ss` (and `-t`) stopped trimming the file and I mistook it for input seeking not working. In fact, the source `-i` was always before.

Now it's moved next to the metafile `-i` and moving both after `-ss` (and `-t`) for input seeking works.

**Comment by mkb79** [comment]
Note:
I’ve found [this](https://forum.videohelp.com/threads/403057-Split-M4B-audiobook-to-chapters-without-conversion#post2634997) user comment about splitting a M4B file into chapters using mkvmerge. Maybe this can be an enhancement to the decrypt command in the future?!

Note2:
I does not have tested your code yet. But if it works, the decrypt command can be moved to the build-in commands?!

**Comment by vwkd** [comment]
If I read the post correctly, they’re doing the same thing. They just want to split each chapter into a separate output file. We should already be lossless with `-c copy` which doesn’t re-encode. Another benefit to not re-encoding is it’s much faster. You can test using`-c copy -c:a aac` which re-encodes the audio stream to aac, which on my machines takes quite some time for a lengthy audio book.

I agree, with this the current set of functionality of `decrypt` covers my own basic needs. It could be a good starting point for a built-in command which would make it easier to use and hopefully drive more contributions in the future.

**Comment by vwkd** [comment]
@mkb79 Were you able to test this yet?

The code isn’t really complicated. It removes the intro and outro chapters, and shifts the starting times of all chapters forward by the intro duration. It gets the new starting time from the starting time of the first chapter and the new duration from `old duration - intro duration - outro duration`. Then it passes everything to ffmpeg.

**Comment by mkb79** [comment]
@vwkd 
The code looks good. To be honest, I didn't test it. Can you make sure that ffmpeg can cut the files correctly?

**Comment by vwkd** [comment]
@mkb79 Were you able to test this?

**Comment by mkb79** [comment]
@vwkd 
To be true, I doesn’t have tested it. But I will do it this week. I was also thinking about either build in the commando or bringing it to PyPI as an extra package and using a ffmpeg binding for Python. What do you mean?

**Comment by vwkd** [comment]
Great.

I think making the `decrypt` plugin a built-in command would be great and easier to use. But let's first merge this PR and do that in a separate PR to keep a clean history.

**Review by mkb79 — APPROVED** [review]

**Pull request merged**
